### ISSUE TITLE
Syntax for Entities Name?

### ISSUE THREAD

**Issue by aptonline** [nervetattoo/banner-card#1]
Great custom card however I've finding it hard to override the friendly name using ``entities.name``.  Can you give an example of usage?

**Comment by nervetattoo** [comment]
This is what I have once place:

```yaml
    entities:
      - entity: light.fibaro_system_fgd212_dimmer_2_level_11
        name: Light
```
