### ISSUE TITLE
heading does not include icons

### ISSUE THREAD

**Issue by prankousky** [nervetattoo/banner-card#100]
Hi everybody,

I am trying to set up one `custom:banner-card` per room on my VIP dashboard (containing an overview of the most important entities).

This is my code

```
- type: "custom:banner-card"
  heading: [mdi:star, VIP]
  entities:
    - entity: binary_sensor.zwischenzimmer_tuer_contact
      name: Zwischenzimmer
      icon: mdi:door
    - entity: binary_sensor.draussen_gartentor_contact
      name: Tor
      icon: mdi:door
    - entity: sensor.beidesindda
      name: Beide
      icon: mdi:heart
```

This is the result:

![grafik](https://user-images.githubusercontent.com/11297070/104834483-e03bec80-589f-11eb-8120-44d0a20bbf4b.png)

I have tried different versions for the heading, for example, I changed it to

```
  heading: 
    - "mdi:star"
    - VIP
```

No success.

I have tried different icon values, for example `mdi:heart` (which definitely works with this card, as it is used for the `sensor` above and does show up) and `hass:star`, but they won't work, either.

Can you please help me fix this? 

Thank you in advance :)
