### ISSUE TITLE
Icon's not showing when used as map_state

### ISSUE THREAD

**Issue by a-bianucci** [nervetattoo/banner-card#102]
Leveraging the following code for a card, and trying to change the icon based on state. However I can't even get it to use an icon regardless, much less with state.

```
type: 'custom:banner-card'
background: '#64afd1'
color: '#FFFFFF'
heading:
  - 'mdi:folder-home'
  - Office
entities:
  - entity: light.office_lighting
    name: Lights
    domain: light
    value: 'mdi:lightbulb'
    color: '#64afd1'
    map_state:
      'on':
        color: '#7cde71'
        value: 'mdi:lightbulb'
        name: 'On'
      'off': 'mdi:lightbulb'
```
