### ISSUE TITLE
Custom images for icons in headers

### ISSUE THREAD

**Issue by fabiendostie** [nervetattoo/banner-card#106]
hello, first of all thank you for this wonderful add-on!
I like it a lot, my girlfriend too!!

I have two issues: 
1- I see that its possible to use images as "icons" in the header, but I can't seem to be able to find the way to actually do it... 
could someone please help me with the \ escape thing? I don't understand how or where to put my .png or .svg files to be able to use them.

2- I have successfully set  a switch for a light that calls on a script to dim the lights but it doesn't react like it's supposed to or at least how I was expecting. I am pretty sure it's because I had to use "tap_action" instead of just "action" for it to actually work. I am not well versed in js or coding in general, learning fast but still quite noob and i would really appreciate the help. 

heres the code for the light entity switch in question:
```
type: 'custom:banner-card'
background: 'radial-gradient(#286a84,#212527)'
heading: Bureau
row_size: 4
entities:
  - entity: light.70207438b4e62d384747
    name: Lumieres Soir
    tap_action:
      action: call-service
      service: script.turn_on
      icon: 'mdi:moon-rising-crescent'
      service_data:
        entity_id: script.dim_office_light
```

thanks
