### ISSUE TITLE
Icons for switch and light is not working

### ISSUE THREAD

**Issue by estevez-dev** [nervetattoo/banner-card#111]
Banner card version: 0.13.0
Home Assistant version: 2021.4.3

Card configuration:
```
type: 'custom:banner-card'
heading:
  - Kitchen
background: '#81559B'
entities:
  - entity: light.kitchen
    name: Light
    value: 'mdi:ceiling-light'
  - entity: switch.kitchen_tv
    value: 'mdi:television'
    name: TV
```

Result:
![screenshot-homeassistant_8123-2021 04 12-13_50_49](https://user-images.githubusercontent.com/1819786/114383537-534eb980-9b96-11eb-905f-683e2bb72235.png)
