### ISSUE TITLE
Enhancement - Tap to execute script entities

### ISSUE THREAD

**Issue by kethoth** [nervetattoo/banner-card#12]
I have a script to activate the nightlight hue scene and have added the script as an entity to the banner-card.  It would be nice if I could execute the script by tapping that part of the card; currently it opens more info which has an execute button.

Alternatively, is it possible to add tap_action customization options?

**Comment by nervetattoo** [comment]
I want config to be simple and lightweight with sane defaults over deep customisation options, thus I don't like the action/tap_action config support I'm seeing elsewhere. For scripts I guess one wouldn't add a script to this card if running it was dangerous so there shouldn't be much harm in just supporting that with a button somehow. Will a single button be enough? I mean,  is it any meta data about the script that is needed to make this usable?

**Comment by kethoth** [comment]
I can't speak for others, but mine is just a service call to turn on the
light with a specific Hue scene so a button would be fine.

**Comment by kethoth** [comment]
```
      - type: custom:banner-card
        heading: "\U0001F6CF Bedroom"
        entities:
          - light.bedroom
          - entity: sensor.aqara_temperature
            name: Temp
          - entity: binary_sensor.aqara_motion
            name: Motion
          - light.closet
          - entity: sensor.lumi_lumi_sensor_motion_aq2_02f39828_1_1024
            name: Lux
          - entity: script.bedroom_nightlight_hue_scene
            name: Nightlight
            value: mdi:lamp
            action:
              service: homeassistant.turn_on  
```

Renders 
![image](https://user-images.githubusercontent.com/46651681/58730264-34374c00-83b1-11e9-9f6b-8c46f2457fad.png)
 
Clicking on Nightlight renders this pop-up instead of executing the service.  I can manually execute homeassistant.turn_on for script.bedroom_nightlight_hue_scene and it executes the script, as does the execute button in the pop-up.
![image](https://user-images.githubusercontent.com/46651681/58730343-72347000-83b1-11e9-827f-faf36c148878.png)
