### ISSUE TITLE
show icon for entity instead of the name

### ISSUE THREAD

**Issue by ChristophCaina** [nervetattoo/banner-card#128]
Hi,
I would like to show an Icon instead of the name for an entity.
Unfortunately, it seems that this isn't working.

As soon as I configure the Icon for the entity, the state is gone.

![grafik](https://user-images.githubusercontent.com/26391061/136187168-ade68548-42c0-4cbe-a0ef-5f5af450e5b5.png)

```
type: custom:banner-card
background: '#fff2cc'
row_size: 4
heading: Terrarium 1
entities:
  - entity: sensor.t1_animal_name
    name: null
  - entity: sensor.t1_animal_fam
    name: null
  - entity: binary_sensor.t1_daylight
    name: Tageslicht
  - entity: binary_sensor.t1_heating
    name: Wärme
  - entity: sensor.t1_temperature
    name: null
  - entity: sensor.t1_humidity
    name: null
  - entity: sensor.t1_daylight_sunrise
    icon: mdi:weather-sunset-up
    name: 
  - entity: sensor.t1_daylight_sunset
    name: Sonnenuntergang
    icon: mdi:weather-sunset-down
```
