### ISSUE TITLE
map_state example from documentation not working

### ISSUE THREAD

**Issue by yesterdayshero** [nervetattoo/banner-card#138]
Trying to use the **map_state** function based on the example in the [documentation](https://github.com/nervetattoo/banner-card) and it isn't working. 

If I apply the same settings in Home Assistant, I still get the media player title showing in the Banner Card, rather than the values entered in the **map_state** code.

```
entity: media_player.office
map_state:
  playing: mdi:disc-player
  not_playing:
    value: mdi:stop
    name: A custom entity heading
```

![media player in banner card](https://user-images.githubusercontent.com/74452772/154191338-11577d28-1186-4e4d-905c-db1422ff359c.png)

**Comment by luixal** [comment]
I'm hitting the same problem. In my case, I'm using the banner card to show some simple on/off switches (used for sprinklers) this way:

```yaml
type: custom:banner-card
heading:
  - mdi:sprinkler-variant
  - Garden Irrigation
background: '#EDE7BA'
entities:
  - entity: switch.sprinkler_3
    name: '3'
    map_state:
      'on':
        value: mdi:sprinkler-variant
        name: 'on'
      'off':
        value: mdi:sprinkler-variant
        name: 'off'
```

In my case, the `name` field is showing right ("on" when switch is on and "off" when it's off) but icon nevers shows up. I've tried removing the `name` field (just in case it has priority over the icon or something); icons are still not showing.

I've also tried removing all `name` fields (the entity one too) and then entity's name is showed.

Any ideas on this?

Thanks!
