### ISSUE TITLE
map_state not working

### ISSUE THREAD

**Issue by CatMonster** [nervetattoo/banner-card#14]
Is this the supposed way to use ```map_state``` to set an icon instead of state?

```
  - type: custom:banner-card
    background: "#37474F"
    heading: "APC UPS"
    entities:
      - entity: binary_sensor.ups_online_status
        name: Status
        map_state: 
          on: mdi:check
          off: mdi:close
```

**Comment by nervetattoo** [comment]
You can never use `on` or `off` as keys directly in YAML for HA like you're doing. They get interpreted to be `true` / `false` 😿 Write it in quotation marks to get around it:

```yaml
map_state:
  "on": mdi:check
  "off": mdi:close
```

This is SO annoying and so many people get bitten by it.

**Comment by CatMonster** [comment]
tried with another device with another state, but I can't get working even with quotes
```
- type: custom:banner-card
    background: "#FFA726"
    heading: "La governante"
    entities:
      - entity: vacuum.la_governante
        name: Status
        map_state:
          docked: mdi:close
```
