### ISSUE TITLE
how to set white  backgroud and black font  

### ISSUE THREAD

**Issue by 0neday** [nervetattoo/banner-card#143]
I set 

```
type: custom:banner-card
heading: false
background: white
entities:
  - entity: sensor.date
    name: 日期
  - entity: sensor.week
    name: 星期
  - entity: sensor.time
    name: 时间
```
![捕获.JPG](https://s2.loli.net/2022/05/18/RcQn7o3tLHwYxrq.jpg)
