### ISSUE TITLE
Is it possible to display an entity value in the header?

### ISSUE THREAD

**Issue by viktak** [nervetattoo/banner-card#158]
As a the title says: Instead of a static text/icon combo, is it possible to display an entity's value?

Something like this:
```
  - type: custom:banner-card
    heading:
      - mdi:server
      - VPS
      - entity: sensor.my_hostname
```

thanks for the card!!
