### ISSUE TITLE
map_state to values from multiple entities

### ISSUE THREAD

**Issue by udayms** [nervetattoo/banner-card#159]
I am trying to show 3 different states of a door on my banner. I want to show different icons for each state of my door.

- OPEN
- CLOSED
- LOCKED

The OPEN and CLOSED states can be read from a contact sensor entity.
The LOCKED state can be read from a Schlage ZWave Lock.

Today, I am showing it as two items in the banner-card. How can I show all these on a single item?

```
type: custom:banner-card
heading:
  - 🚪 Doors
background: '#b72856'
color: '#ffffff'
row_size: auto
entities:
  - entity: lock.XXXXXXX
    name: Front Door Lock
    value: mdi:lock
    map_state:
      unlocked:
        color: '#d9d152'
        value: mdi:lock-open
      locked:
        color: '#ffffff'
        value: mdi:lock
    lock: open
  - entity: binary_sensor.YYYYYY
    name: Front Door
    value: mdi:door-closed-lock
    map_state:
      'on':
        color: '#d9d152'
        value: mdi:door-open
      'off':
        color: '#ffffff'
        value: mdi:door-closed
```
