### ISSUE TITLE
Formatting attributes?

### ISSUE THREAD

**Issue by proffalken** [nervetattoo/banner-card#161]
Hey folks, 

I'm hoping I can somehow format the attribute of one of my sensors into something like `3 hours from now` or `5pm tonight`

My config is as follows:

```yaml
type: custom:banner-card
heading:
  - mdi:home
  - Home
entities:
  - entity: device_tracker.me
    name: Me
  - entity: device_tracker.my_wife
    name: My Wife
  - entity: device_tracker.kid_no_1
    name: Kid No. 1
  - entity: device_tracker.kid_no_2
    name: Kid No. 2
    value: School
  - type: custom:simple-weather-card
    entity: weather.home_2
  - entity: binary_sensor.octopus_energy_saving_session
    attribute: next_joined_event_start
    name: Next Energy Saving Session
    size: 4
row_size: 4
```

Any ideas what I can use here?

![image](https://github.com/nervetattoo/banner-card/assets/262545/b296a779-f874-4fa1-85e7-ce29d5cc9313)
