### ISSUE TITLE
icon replacement

### ISSUE THREAD

**Issue by mclaudiopt** [nervetattoo/banner-card#28]
Hello 
i am trying to change the slider on off for an icon
my code is:
```
type: 'custom:banner-card'
heading: "\U0001F6C1 Toalheiros"
background: '#B0C2ED'
link: /lovelace/bathroom
entities:
  - entity: switch.toalheiro_wc_visitas
    name: Visitas
    map_state: null
    'on': 'mdi:home-account'
    'off': 'mdi:walk'
    show_icon: true
    show_value: true
  - entity: switch.toalheiro_wc_1a
    name: 1º Andar
  - entity: switch.toalheiro_wc_suite
    name: Suite
``` 
but it does not work. any ideias?
thanks
