### ISSUE TITLE
Feature request covers

### ISSUE THREAD

**Issue by mclaudiopt** [nervetattoo/banner-card#29]
hello
it would be great to integrate this into the banner
is it possible?
thanks
```
entities:
  - entity: cover.estore_cozinha
    full_row: false
    icon: 'mdi:blinds'
    name: Cozinha
    type: 'custom:slider-entity-row'
title: null
type: entities
```
![image](https://user-images.githubusercontent.com/48178294/60904644-46878e00-a26b-11e9-81b9-4d88242a6149.png)
