### ISSUE TITLE
Feature request: Conditional card

### ISSUE THREAD

**Issue by MetalWing** [nervetattoo/banner-card#37]
As a user I would like to have the ability to:
 - Show or Hide the entire banner card when a condition is met

Example:
![image](https://user-images.githubusercontent.com/1570136/62055336-6a465000-b1e9-11e9-8041-de219f0aefbc.png)

**Expected:**
When there are no alerts, the banner card should not be visible at all

**Actual:**
When there are no alerts, the banner card is present, with only the title shown.
![image](https://user-images.githubusercontent.com/1570136/62055427-9bbf1b80-b1e9-11e9-8404-c33e08237bb5.png)

**Comment by MetalWing** [comment]
This can be achieved by wrapping the banner card in a Conditional Card. As such:

```
card:
  background: '#fab234'
  entities:
    - entity: sensor.warnings
      name: null
      when:
        attributes:
          hidden: false
    - entity: sensor.statements
      name: null
      when:
        attributes:
          hidden: false
    - entity: sensor.advisories
      name: null
      when:
        attributes:
          hidden: false
    - entity: sensor.watches
      name: null
      when:
        attributes:
          hidden: false
  heading: ⚠ Weather Alerts
  type: 'custom:banner-card'
conditions:
  - entity: sensor.warnings
    state_not: null'
title: Weather Alerts
type: conditional
```

The only downside is the limitation of the conditional card that does not allow you to have OR conditions.
