### ISSUE TITLE
Feature Request: [when: {{state(domain.entity)}} , "on/off"]

### ISSUE THREAD

**Issue by AtticusG3** [nervetattoo/banner-card#43]
Is it possible to implement a when statement with reference to another entities state?

eg:

```
type: 'custom:banner-card'
background: '#B0C2ED'
entities:
  - entity: light.dining_room
    name: Dining
  - entity: script.1561637538159
    icon: 'mdi:lightbulb'
    name: Colour
    action:
      service: script.1561637538159
    when: [{{states("light.dining_room")}},"on"]
heading: "Light"
```

**Comment by kernel610** [comment]
This is an old request/question but this is already possible with the correct syntax. Try this.

```
type: 'custom:banner-card'
background: '#B0C2ED'
entities:
  - entity: light.dining_room
    name: Dining
  - entity: script.1561637538159
    icon: 'mdi:lightbulb'
    name: Colour
    action:
      service: script.1561637538159
    when:
      entity: light.dining_room
      state:
        - '='
        - 'on'
heading: "Light"
```
