### ISSUE TITLE
feature request: responsive background image

### ISSUE THREAD

**Issue by aaamoeder** [nervetattoo/banner-card#48]
I'm using this card for the persons page of our HA dashboard and I'd love to be able to show people's picture as background and have it grayed out when not home..

Great work on the card, VERY useful ! thanks !

**Comment by jokerigno** [comment]
+1 on this. I have a custom view for mobile agend and would be great to use a background image for every card.

This is what I've done using picture elements:

![image](https://user-images.githubusercontent.com/23552762/69232523-851f4480-0b8b-11ea-9be2-936cfefd7d13.png)

**Comment by nervetattoo** [comment]
Are you talking about the card background or an image for an entity?
You can set a card background image like this:

```yaml
type: custom:banner-card
background: 'url("https://source.unsplash.com/random/500x300")'
heading: Image bacground
```

You can't however make it gray based on some state.

For entities you can use `map_state` to use one image for `home` and another for `away`.
```yaml
entity: person.bill
image: true
map_state:
  home:
    value <image url for home image>
  away:
    value: <image url for away image>
```
