### ISSUE TITLE
Help: Theming Buttons

### ISSUE THREAD

**Issue by DickSwart** [nervetattoo/banner-card#49]
Hope someone can help, is it possible to theme the buttons? I have the following values in my custom theme but the buttons stay white.
```yaml
    paper-toggle-button-checked-button-color: '#4ab52f'
    paper-toggle-button-checked-bar-color: '#4ab52f'
    paper-toggle-button-checked-ink-color: '#4ab52f'
```
