### ISSUE TITLE
Havinig issues with Inline modifications of banner css

### ISSUE THREAD

**Issue by johntdyer** [nervetattoo/banner-card#62]
I am trying to resize the banner inline and I am not sure how to go about it.  I tried card-modder but it doesnt seem to work... 

```yaml
    - type: vertical-stack
        cards:
          - type: custom:banner-card
            background: "#EDE7B0"
            heading: "\U0001F6CB Living room"
            # link: /lovelace/living_room
            style: |
              .heading {
                display: block;
                font-size: var(--bc-font-size-heading);
                font-weight: 150;
                cursor: pointer;
                align-self: stretch;
                text-align: center;
              }
            entities:

          - type: horizontal-stack
            cards:

              - type: custom:button-card
                template: homekit_light
                entity: switch.living_room_hallway
                name: living hall
                icon: mdi:lightbulb

              - type: custom:button-card
                template: homekit_dimmer
                entity: light.living_room_chandelier
                name: living room
                icon: 'bha:chandelier'

              - type: custom:button-card
                template: homekit_light
                entity: light.jackies_office_dimmer
                name: jackies office
                icon: 'bha:ceiling-lamp-round'

              - type: "custom:button-card"
                color_type: blank-card
              - type: "custom:button-card"
                color_type: blank-card
```

Any ideas
