### ISSUE TITLE
map_state: color does not change icon color

### ISSUE THREAD

**Issue by swampylee** [nervetattoo/banner-card#68]
Hi, love the banner card, thank you! I'm trying to change icon and color using map_state: but only the icon changes and not the color. I'm following the example you use in your readme.md:

```
Using map_state to render a switch as a colored icon

- entity: switch.switch
  name: Is it on?
  domain: sensor
  value: mdi:star
  color: black
  map_state:
    "on":
      color: yellow
```
I see there is mention of map_state color changes but I assumed that as it was specifically used in an example that this should now be working.
