### ISSUE TITLE
How to reduce the space in red area

### ISSUE THREAD

**Issue by sasukebinbin** [nervetattoo/banner-card#76]
![living-room](https://user-images.githubusercontent.com/36916438/82339655-db791d00-9a20-11ea-900f-430ef76b9af8.png)

**Comment by ktownsend-personal** [comment]
I agree! This is the very first thing I wanted to change when I started using this card. I love the simple and clean layout of this card, but that margin is enormous when you reduce the heading size. I'm trying to use this on a tablet wall panel where space is at a premium.

**Comment by ktownsend-personal** [comment]
@sasukebinbin today's release added a template variable for the heading margin to fix this: --banner-card-heading-margin

**Comment by sasukebinbin** [comment]
Awesome

**Comment by gasm67** [comment]
Would it be possible for someone to give me some advice on how to accomplish this (possibly with an example) ?  I have been trying to follow the instructions in the repository, and this is the only thing I'm having difficulty in understanding..
Many Thanks in advance....

**Comment by ktownsend-personal** [comment]
@gasm67 you can put the settings in your theme file, which is likely in your `/config/themes` folder.

Here are a few settings I have in my theme for this card:

```yaml
  banner-card-heading-size: 1.5em
  banner-card-media-title-size: 0.7em
  banner-card-entity-value-size: 1.2em
  banner-card-spacing: 0.135em
  banner-card-heading-margin: 0.3em
```
