### ISSUE TITLE
HA 0.110 related issues

### ISSUE THREAD

**Issue by afxefx** [nervetattoo/banner-card#77]
No rush, but wanted to let you know that 0.110 is causing some aesthetic issues with this awesome card due to changes in the way icons are handled now.  

Cover icons aren't showing, although they are still present.  Also my toggles have picked up a different color when a device is turned off.  All non-banner-card toggles are unaffected.

<img width="502" alt="Screen Shot 2020-05-21 at 4 15 59 PM" src="https://user-images.githubusercontent.com/3475494/82602138-a08cfb80-9b7e-11ea-8823-7f9b398336a7.png">

**Comment by gizbod** [comment]
this also applies to media player in the card.
![bannercard](https://user-images.githubusercontent.com/18351060/82731496-44051a00-9cff-11ea-9d0e-7fa2c103778c.png)

**Comment by swampylee** [comment]
And any mdi: icons in the headers are now much smaller

**Comment by SeraphimSerapis** [comment]
+1 to this. I tried fixing this locally but haven't found the "proper way" to do so. 

Regarding size: it seems like `--mdc-icon-size: 100%;` in `ha-card` needs to be set: https://github.com/custom-cards/button-card/commit/89a842a9b3f8004eab2063a77f3bfbde62ea5831

**Comment by tchellomello** [comment]
Hitting the same issue for cover icons

```yaml
background: '#1ac6ff'
entities:
  - entity: binary_sensor.garage_motion
    map_state:
      'on':
        value: 'mdi:motion-sensor'
    size: 1
    value: 'mdi:walk'
  - entity: binary_sensor.garage_motion
    map_state:
      'on':
        value: 'mdi:motion-sensor'
    name: Camera Motion
    size: 2
    value: 'mdi:walk'
  - entity: sensor.garage_hu_temp_uv_temperature
    name: Temperature
  - entity: sensor.garage_hu_temp_uv_lux
    name: Lux
  - entity: sensor.garage_hu_temp_uv_humidity
    name: Humitiy
  - entity: binary_sensor.internal_garage_door
    map_state:
      'on':
        value: 'mdi:door-open'
    value: 'mdi:door-closed-lock'
    size: 3
  - entity: switch.driveway
  - entity: switch.front_porch
  - entity: switch.garage_lights
  - entity: cover.double_garage_door
    size: 2
  - entity: cover.single_garage_door
  - entity: binary_sensor.double_car_garage_door
    map_state:
      'on':
        value: 'mdi:garage-open-variant'
    name: 
    size: 2
    value: 'mdi:garage-variant'
  - entity: binary_sensor.single_car_garage_door
    map_state:
      'on':
        value: 'mdi:garage-open'
    name: 
    value: 'mdi:garage-variant'
heading: "\U0001F698 Garage"
row_size: 3
type: 'custom:banner-card'
```

![image](https://user-images.githubusercontent.com/809840/83109731-e6baf100-a08f-11ea-80f5-28b5931639b9.png)
