### ISSUE TITLE
Adding "service:" within the action object changes the font of the displayed state/attribute

### ISSUE THREAD

**Issue by strikeir13** [nervetattoo/banner-card#83]
Banner Card Version: 0.11.0
HACS Version: 1.1.2
HA Version: 0.112.2
Supervisor: 228

When "service:" is added within the action object, the font for the displayed state/attribute changes to all small caps. This also affects the overall card height. 

Example with "service:" and nothing specified:
```
background: lightgreen
entities:
  - entity: sensor.bedroom_temperature_2
    name: Temperature
    action:
      service:
heading:
  - 'mdi:hotel'
  - Bedroom
row_size: 3
type: 'custom:banner-card'
```
![image](https://user-images.githubusercontent.com/688283/86801084-474b2f80-c039-11ea-8232-48fb453ecc77.png)

When "service:" is removed, the font is displayed as it should be:
```
background: lightgreen
entities:
  - entity: sensor.bedroom_temperature_2
    name: Temperature
    action:
heading:
  - 'mdi:hotel'
  - Bedroom
row_size: 3
type: 'custom:banner-card'
```
![image](https://user-images.githubusercontent.com/688283/86801197-62b63a80-c039-11ea-9d28-a4299309dfe1.png)

The same is true if an attribute is displayed:
```
background: lightgreen
entities:
  - entity: sensor.bedroom_temperature_2
    name: Temperature
    action:
      service:
    attribute: friendly_name
heading:
  - 'mdi:hotel'
  - Bedroom
row_size: 3
type: 'custom:banner-card'
```
![image](https://user-images.githubusercontent.com/688283/86802180-5b436100-c03a-11ea-91dc-aee4260bdd31.png)

```
background: lightgreen
entities:
  - entity: sensor.bedroom_temperature_2
    name: Temperature
    action:
    attribute: friendly_name
heading:
  - 'mdi:hotel'
  - Bedroom
row_size: 3
type: 'custom:banner-card'
```
![image](https://user-images.githubusercontent.com/688283/86802239-6d250400-c03a-11ea-9d76-3a8c6cd16f17.png)
