### ISSUE TITLE
When not unavailable

### ISSUE THREAD

**Issue by Giom-V** [nervetattoo/banner-card#89]
I've been trying to only show my Chromecast when it's playing and for some reason, I'm not able to filter out the "unavailable" state.

Here's what I tried:
```
  - entity: media_player.tv
    when:
      state:
        - '!='
        - 'Off'
        - 'Unavailable'
```

Is there any way to make it work?
