### ISSUE TITLE
Exclamation mark over pictures since 0.117.x

### ISSUE THREAD

**Issue by BertrumUK** [nervetattoo/banner-card#95]
Since carrying out the update to 0.117 there has been an exclamation mark over every picture when using "map_state"

![banner](https://user-images.githubusercontent.com/22644029/98165614-1cd18c00-1ede-11eb-842a-1b164a34b59e.png)

This has also been reported by at least 1 other person since this update. 

Here is my code

```yaml
background: '#66CDAA'
color: lime
entities:
  - entity: group.neil
    image: true
    map_state:
      home: /local/neil.jpg
      not_home: /local/away.jpg
    name: Neil
  - entity: group.julie
    image: true
    map_state:
      home: /local/julie.jpg
      not_home: /local/away.jpg
    name: Julie
  - entity: group.alex
    image: true
    map_state:
      home: /local/alex.jpg
      not_home: /local/away.jpg
    name: Alex
  - entity: group.cerys
    image: true
    map_state:
      home: /local/cerys.jpeg
      not_home: /local/away.jpg
    name: Cerys
heading: "\U0001F3E1 Family"
link: /lovelace/living_room
row_size: 4
tap_action:
  action: navigate
  navigation_path: /lovelace/0
type: 'custom:banner-card'
```
